import { packMonochrome, type MonochromeBitmap } from "../image/bitmap.ts";
import { requireCIdentifier } from "./c-identifier.ts";
import { niceViewGenerator } from "./metadata.ts";

/**
 * Matches ZMK nice_view/widgets/art.c at the revision in metadata.ts, and the
 * pinned LVGL 9 bin decoder's decode_indexed_line(): two BGRA8888 palette
 * entries, then I1 indices, MSB-first. EACH row starts at a byte boundary.
 * A 140x68 image therefore has an 18-byte stride and 8 + 18*68 = 1232 bytes.
 * Padding bits are zero. Alpha is opaque. The palette is deliberately fixed:
 * editor inversion is baked into pixels, independent of status-widget inversion.
 * Explicit magic/stride use LVGL 9's descriptor rather than legacy inference.
 */
export function encodeLvglImage(bitmap: MonochromeBitmap) {
  const packed = packMonochrome(bitmap);
  const data = new Uint8Array(8 + packed.length);
  data.set([0, 0, 0, 255, 255, 255, 255, 255]);
  data.set(packed, 8);
  return { data, stride: Math.ceil(bitmap.width / 8) };
}

export function generateLvglImage(
  bitmap: MonochromeBitmap,
  artworkName: string,
) {
  const symbol = requireCIdentifier(artworkName);
  const { data, stride } = encodeLvglImage(bitmap);
  const lines: string[] = [];
  for (let i = 8; i < data.length; i += stride) {
    lines.push(
      `    ${Array.from(data.subarray(i, i + stride), (value) => `0x${value.toString(16).padStart(2, "0")}`).join(", ")},`,
    );
  }
  return `/* Generated by ZMK Display Studio
 * Generator: ${niceViewGenerator.id} v${niceViewGenerator.version}
 * ZMK: ${niceViewGenerator.zmkRevision}
 * LVGL I1: ${bitmap.width}x${bitmap.height}, ${stride} bytes/row, ${data.length} bytes including palette.
 * Fixed palette: editor inversion is already applied to pixel data.
 */
#include <lvgl.h>

#if LVGL_VERSION_MAJOR != 9
#error "This artwork targets ZMK's LVGL 9 image API."
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t ${symbol}_map[] = {
    0x00, 0x00, 0x00, 0xff, /* index 0: opaque black (BGRA) */
    0xff, 0xff, 0xff, 0xff, /* index 1: opaque white (BGRA) */
${lines.join("\n")}
};

const lv_image_dsc_t ${symbol} = {
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.cf = LV_COLOR_FORMAT_I1,
    .header.flags = 0,
    .header.w = ${bitmap.width},
    .header.h = ${bitmap.height},
    .header.stride = ${stride},
    .data_size = ${data.length},
    .data = ${symbol}_map,
};
`;
}
